
package orderWebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderWS", targetNamespace = "http://orderWebservice/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface OrderWS {

  public final static String DEPLOYMENT_PATH = "http://localhost:8083/OrderWS";


    /**
     * 
     * @param password
     * @param xml
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "placeOrder")
    @WebResult(name = "success", partName = "success")
    @Action(input = "placeOrder", output = "http://orderWebservice/OrderWS/placeOrderResponse")
    public String placeOrder(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "xml", partName = "xml")
        String xml);

}
