
package orderWebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderWSService", targetNamespace = "http://orderWebservice/", wsdlLocation = "http://139.174.101.123:8083/OrderWS?wsdl")
public class OrderWSService
    extends Service
{

    private final static URL ORDERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERWSSERVICE_EXCEPTION;
    private final static QName ORDERWSSERVICE_QNAME = new QName("http://orderWebservice/", "OrderWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://139.174.101.123:8083/OrderWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERWSSERVICE_WSDL_LOCATION = url;
        ORDERWSSERVICE_EXCEPTION = e;
    }

    public OrderWSService() {
        super(__getWsdlLocation(), ORDERWSSERVICE_QNAME);
    }

    public OrderWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERWSSERVICE_QNAME, features);
    }

    public OrderWSService(URL wsdlLocation) {
        super(wsdlLocation, ORDERWSSERVICE_QNAME);
    }

    public OrderWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERWSSERVICE_QNAME, features);
    }

    public OrderWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderWS
     */
    @WebEndpoint(name = "OrderWSPort")
    public OrderWS getOrderWSPort() {
        return super.getPort(new QName("http://orderWebservice/", "OrderWSPort"), OrderWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderWS
     */
    @WebEndpoint(name = "OrderWSPort")
    public OrderWS getOrderWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://orderWebservice/", "OrderWSPort"), OrderWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERWSSERVICE_EXCEPTION!= null) {
            throw ORDERWSSERVICE_EXCEPTION;
        }
        return ORDERWSSERVICE_WSDL_LOCATION;
    }

}
