
package marketWebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MarketWS", targetNamespace = "http://marketWebservice/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MarketWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://marketWebservice/MarketWS/getBestOfferRequest", output = "http://marketWebservice/MarketWS/getBestOfferResponse")
    public String getBestOffer(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://marketWebservice/MarketWS/updateRawMaterialsRequest", output = "http://marketWebservice/MarketWS/updateRawMaterialsResponse")
    public String updateRawMaterials(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
