
package marketWebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MarketWSService", targetNamespace = "http://marketWebservice/", wsdlLocation = "http://139.174.101.123:8082/MarketWS?wsdl")
public class MarketWSService
    extends Service
{

    private final static URL MARKETWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MARKETWSSERVICE_EXCEPTION;
    private final static QName MARKETWSSERVICE_QNAME = new QName("http://marketWebservice/", "MarketWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://139.174.101.123:8082/MarketWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MARKETWSSERVICE_WSDL_LOCATION = url;
        MARKETWSSERVICE_EXCEPTION = e;
    }

    public MarketWSService() {
        super(__getWsdlLocation(), MARKETWSSERVICE_QNAME);
    }

    public MarketWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MARKETWSSERVICE_QNAME, features);
    }

    public MarketWSService(URL wsdlLocation) {
        super(wsdlLocation, MARKETWSSERVICE_QNAME);
    }

    public MarketWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MARKETWSSERVICE_QNAME, features);
    }

    public MarketWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarketWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MarketWS
     */
    @WebEndpoint(name = "MarketWSPort")
    public MarketWS getMarketWSPort() {
        return super.getPort(new QName("http://marketWebservice/", "MarketWSPort"), MarketWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarketWS
     */
    @WebEndpoint(name = "MarketWSPort")
    public MarketWS getMarketWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://marketWebservice/", "MarketWSPort"), MarketWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MARKETWSSERVICE_EXCEPTION!= null) {
            throw MARKETWSSERVICE_EXCEPTION;
        }
        return MARKETWSSERVICE_WSDL_LOCATION;
    }

}
