
package marketWebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MarketWSServerService", targetNamespace = "http://marketWebservice/", wsdlLocation = "http://localhost:8082/MarketWS?wsdl")
public class MarketWSServerService
    extends Service
{

    private final static URL MARKETWSSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MARKETWSSERVERSERVICE_EXCEPTION;
    private final static QName MARKETWSSERVERSERVICE_QNAME = new QName("http://marketWebservice/", "MarketWSServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/MarketWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MARKETWSSERVERSERVICE_WSDL_LOCATION = url;
        MARKETWSSERVERSERVICE_EXCEPTION = e;
    }

    public MarketWSServerService() {
        super(__getWsdlLocation(), MARKETWSSERVERSERVICE_QNAME);
    }

    public MarketWSServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MARKETWSSERVERSERVICE_QNAME, features);
    }

    public MarketWSServerService(URL wsdlLocation) {
        super(wsdlLocation, MARKETWSSERVERSERVICE_QNAME);
    }

    public MarketWSServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MARKETWSSERVERSERVICE_QNAME, features);
    }

    public MarketWSServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarketWSServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MarketWS
     */
    @WebEndpoint(name = "MarketWSPort")
    public MarketWS getMarketWSPort() {
        return super.getPort(new QName("http://marketWebservice/", "MarketWSPort"), MarketWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarketWS
     */
    @WebEndpoint(name = "MarketWSPort")
    public MarketWS getMarketWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://marketWebservice/", "MarketWSPort"), MarketWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MARKETWSSERVERSERVICE_EXCEPTION!= null) {
            throw MARKETWSSERVERSERVICE_EXCEPTION;
        }
        return MARKETWSSERVERSERVICE_WSDL_LOCATION;
    }

}
